In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

In [ ]:
# Read the dataset

In [3]:
df = pd.read_csv('kyphosis.csv')

In [ ]:
# Overview the dataset

In [4]:
df.head()

Kyphosis  Age  Number  Start
0   absent   71       3      5
1   absent  158       3     14
2  present  128       4      5
3   absent    2       5      1
4   absent    1       4     15

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Kyphosis  81 non-null     object
 1   Age       81 non-null     int64 
 2   Number    81 non-null     int64 
 3   Start     81 non-null     int64 
dtypes: int64(3), object(1)
memory usage: 2.7+ KB


In [ ]:
# train test split

In [10]:
from sklearn.model_selection import train_test_split

In [ ]:
# drop target's column

In [11]:
x = df.drop('Kyphosis',axis=1)
y = df['Kyphosis']

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30)

In [ ]:
# Predictions and Evaluations with DecisionTree algorithm

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
dtree = DecisionTreeClassifier()

In [16]:
dtree.fit(x_train,y_train)

DecisionTreeClassifier()

In [17]:
predictions = dtree.predict(x_test)

In [19]:
from sklearn.metrics import classification_report,confusion_matrix

In [20]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

      absent       0.80      0.80      0.80        20
     present       0.20      0.20      0.20         5

    accuracy                           0.68        25
   macro avg       0.50      0.50      0.50        25
weighted avg       0.68      0.68      0.68        25



In [21]:
print(confusion_matrix(y_test,predictions))

[[16  4]
 [ 4  1]]


In [ ]:
# Predictions and Evaluations with RandomForest algorithm

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
rfc = RandomForestClassifier(n_estimators=100)

In [32]:
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [33]:
rfc_pred = rfc.predict(x_test)

In [34]:
print(confusion_matrix(y_test,rfc_pred))

[[15  5]
 [ 4  1]]


In [35]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

      absent       0.79      0.75      0.77        20
     present       0.17      0.20      0.18         5

    accuracy                           0.64        25
   macro avg       0.48      0.47      0.48        25
weighted avg       0.66      0.64      0.65        25



In [ ]:
# Predictions and Evaluations with LogisticRegression algorithm

In [36]:
from sklearn.linear_model import LogisticRegression

In [38]:
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression()

In [39]:
predictions = logmodel.predict(x_test)

In [40]:
confusion_matrix(y_test,predictions)

array([[17,  3],
       [ 4,  1]], dtype=int64)

In [42]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

      absent       0.81      0.85      0.83        20
     present       0.25      0.20      0.22         5

    accuracy                           0.72        25
   macro avg       0.53      0.53      0.53        25
weighted avg       0.70      0.72      0.71        25

